name: flutter_mtg_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  google_mlkit_text_recognition: ^0.12.1
  hooks_riverpod: ^2.5.1
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5
  json_annotation: ^4.4.0
  http: ^1.1.0
  dio: ^5.4.3+1
  scryfall_api: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  json_serializable: ^6.7.1
  

flutter:
  uses-material-design: true
